name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest
      - name: Build Docker image
        run: docker build -t ai-request-handler:latest .
      - name: Push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ai-request-handler:latest
          # Optional: Add Docker Hub credentials if needed
          # dockerhub/username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # dockerhub/password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run linting
        run: flake8 .